### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kishore556** [genomeannotation/annie#10]
I am receiving the following error as : IndexErro: list index out of range" though I used blast_out put file using SWissProt protein database, SwissProt protein database: uniprot_sprot.fasta. Command on DOS prompt is written below.

F:\soft_genome\annie>python2 annie.py -b talaro_in/blast1.out -g talaro_in/gffgenes.gff3 -db talaro_in/uniprot_sprot.fasta  -o gff_out.gff3
Traceback (most recent call last):
  File "annie.py", line 122, in <module>
    main(sys.argv)
  File "annie.py", line 78, in main
    annotations.extend(read_sprot(blast_file, gff_file, fasta_file))
  File "F:\soft_genome\annie\src\sprot.py", line 9, in read_sprot
    gff_info = get_gff_info(gff_file)
  File "F:\soft_genome\annie\src\sprot.py", line 80, in get_gff_info
    key, val = split[0], split[1]
IndexError: list index out of range

**Comment by Juke34** [comment]
You should try on a Unix machine. You can also give a try to another tool for that task: `agat_sp_manage_functional_annotation.pl` from [AGAT](https://github.com/NBISweden/AGAT).
