### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by Gon1976** [genomeannotation/annie#9]
Hi,
I am trying to run annie but I have this error:
python annie.py -b blast_aaJJvsnr -g augustus.gff -db ../../nr/nr.fasta -o annie.gff
Traceback (most recent call last):
  File "annie.py", line 122, in <module>
    main(sys.argv)
  File "annie.py", line 78, in main
    annotations.extend(read_sprot(blast_file, gff_file, fasta_file))
  File "src/sprot.py", line 8, in read_sprot
    fasta_info = get_fasta_info(fasta_file)
  File "src/sprot.py", line 45, in get_fasta_info
    while words[i].find("OS=") == -1:
IndexError: list index out of range

Could be a problem of the fasta file?
The fasta file correspond to the nr.fasta of proteins download from ncbi, which I use to make the blast.
thanks
Gonzalo

**Comment by Juke34** [comment]
On fasta file other than uniprot it will be difficult to make it work. It uses specific attributes in the fasta header that are probably missing in nr.

**Comment by Gon1976** [comment]
so, it will work if I use a database generated with uniprot fasta?
I will missing some annotations. Do you know another alternative?
thanks

**Comment by Juke34** [comment]
> so, it will work if I use a database generated with uniprot fasta?

yes
